import { Router,Request,Response } from "express";
import { requireAuth,userFrom } from "../auth.js";
import { effectiveEntitlement, quotaFor, periodKeyInAppTz } from "../entitlements.js";
import { query } from "../db.js";
import { getMonthlyReview,getMonthlyReviewSource,generateMonthlyReview } from "../monthlyReview.js";
import { usageSummary } from "../usage.js";
export const monthlyReviewsRouter=Router(); monthlyReviewsRouter.use(requireAuth);
monthlyReviewsRouter.get('/current',async(req:Request,res:Response)=>{try{const ownerId=userFrom(req).id, periodKey=periodKeyInAppTz(), review=await getMonthlyReview(ownerId,periodKey), source=await getMonthlyReviewSource(ownerId,periodKey), sub=(await query<any>('SELECT tier,status,current_period_end,granted_by FROM subscriptions WHERE user_id=$1',[ownerId])).rows[0], entitlement=effectiveEntitlement(sub), usage=await usageSummary(ownerId), limit=quotaFor(entitlement.tier,'monthly_review_generation'), current=usage.monthly_review_generation||{used:0,reserved:0}; res.json({periodKey,review,sourceSessionCount:source.length,hasSource:source.length>0,available:entitlement.active&&limit!=='unavailable'&&(limit==='unlimited'||current.used+current.reserved<limit),usage:{used:current.used,reserved:current.reserved,limit}});}catch(e){res.status(503).json({error:'monthly review unavailable'});}});
monthlyReviewsRouter.post('/generate',async(req:Request,res:Response)=>{try{const result=await generateMonthlyReview(userFrom(req).id); if(result.status==='no_source'||result.status==='existing')return res.status(200).json(result); res.json(result);}catch(e:any){if(e?.name==='FeatureUnavailableError')return res.status(403).json({error:'monthly review unavailable on current plan'});if(e?.name==='QuotaExceededError')return res.status(429).json({error:'monthly review quota reached'});res.status(502).json({error:'monthly review generation failed'});}});
