import React, { useEffect, useMemo, useState } from "react";
import { ArrowDown, ArrowLeft, CheckCircle2, CreditCard, ShieldCheck, Sparkles } from "lucide-react";
import { Link } from "react-router-dom";
import { api, type BillingCatalogResponse, type EntitlementsResponse, type MembershipPlansResponse } from "../api";
import PricingComparison from "../components/PricingComparison";
import PricingFaq from "../components/PricingFaq";
import VietQrCheckoutSheet from "../components/VietQrCheckoutSheet";
import { PricingSkeleton } from "../components/ContentSkeleton";
import { useAuth } from "../AuthContext";
import { getCachedBillingCatalog, getCachedEntitlements, getCachedMembershipPlans } from "../membershipCache";
import PageHeader from "../components/PageHeader";

const formatVnd = (amount: number) => `${new Intl.NumberFormat("vi-VN").format(amount)}đ`;

export default function Pricing() {
  const { user } = useAuth();
  const [catalog, setCatalog] = useState<MembershipPlansResponse | null>(null);
  const [billing, setBilling] = useState<BillingCatalogResponse | null>(null);
  const [entitlement, setEntitlement] = useState<EntitlementsResponse | null>(null);
  const [sku, setSku] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { void getCachedMembershipPlans(api.getMembershipPlans).then(setCatalog).catch(() => setError("Membership details are unavailable right now.")); if (user) void getCachedEntitlements(user.id, api.getEntitlements).then(setEntitlement).catch(() => undefined); void getCachedBillingCatalog(api.getBillingCatalog).then(setBilling).catch(() => undefined); }, [user?.id]);
  const deep = useMemo(() => billing?.catalog.filter((item) => item.tier === "deep_reader" && item.available) || [], [billing]);
  const monthly = deep.find((item) => item.period === "month");
  const annual = deep.find((item) => item.period === "year");
  const saving = monthly && annual ? monthly.amountVnd * 12 - annual.amountVnd : null;
  if (!catalog && !error) return <PricingSkeleton />;
  const active = entitlement?.subscription.tier === "deep_reader";
  return <main className="mx-auto max-w-6xl space-y-8 pb-8 sm:space-y-12"><Link to="/account" className="inline-flex min-h-11 items-center gap-1.5 font-sans text-xs font-bold text-natural-stone hover:text-natural-dark"><ArrowLeft className="h-4 w-4" /> Account</Link>
    <section className="relative overflow-hidden rounded-[2rem] border border-natural-sage/20 bg-natural-sage/10 px-5 py-8 sm:px-9 sm:py-12"><PageHeader className="relative max-w-3xl" eyebrow="Membership" title={<>Keep the habit free.<br />Go deeper when a book asks for more.</>} description="Your reading shelf stays yours. Membership adds a source-grounded companion for returning to ideas, asking better questions and connecting what your own sessions hold." actions={<><a href="#comparison" className="inline-flex min-h-11 items-center gap-2 rounded-full border border-natural-border bg-natural-cream px-4 font-sans text-xs font-bold text-natural-dark hover:bg-white"><ArrowDown className="h-3.5 w-3.5" /> See what changes</a>{billing?.enabled && monthly && !active && <button onClick={() => setSku(monthly.id)} className="inline-flex min-h-11 items-center gap-2 rounded-full bg-natural-sage px-4 font-sans text-xs font-bold text-white hover:opacity-90"><Sparkles className="h-3.5 w-3.5" /> Explore Deep Reader</button>}</>} titleClassName="mt-2 text-3xl font-bold tracking-tight text-natural-dark sm:text-5xl" descriptionClassName="mt-4 max-w-2xl text-base leading-relaxed text-natural-stone sm:text-lg" actionsClassName="mt-6" /></section>
    {error ? <p className="rounded-2xl border border-natural-border bg-natural-cream p-4 text-sm text-natural-stone">{error}</p> : <>
      <section className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]" aria-labelledby="deep-reader-heading"><article className="rounded-3xl border border-natural-sage/30 bg-natural-sage/10 p-5 shadow-sm sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-sans text-[10px] font-bold uppercase tracking-[0.16em] text-natural-sage">Most complete reading companion</p><h2 id="deep-reader-heading" className="mt-1 text-3xl font-bold text-natural-dark">Deep Reader</h2><p className="mt-2 max-w-xl text-sm leading-relaxed text-natural-stone">For books you want to carry forward—not simply finish.</p></div>{active && <span className="rounded-full bg-natural-sage px-3 py-1 font-sans text-[10px] font-bold text-white">Your plan</span>}</div><div className="mt-6 grid gap-3 sm:grid-cols-3">{[["Return to the book", "Book Wiki, Reading Lens and Reading Map help hold the thread."], ["Ask from your sessions", "Questions and connections stay grounded in what you have saved."], ["Hear the thread again", "Recap podcast and monthly review help you revisit the month."]].map(([title, copy]) => <div key={title} className="rounded-2xl bg-natural-cream/80 p-4"><CheckCircle2 className="h-4 w-4 text-natural-sage" /><h3 className="mt-3 text-sm font-bold text-natural-dark">{title}</h3><p className="mt-1 text-xs leading-relaxed text-natural-stone">{copy}</p></div>)}</div></article><aside className="rounded-3xl border border-natural-border bg-natural-cream p-5 shadow-sm sm:p-7"><p className="font-sans text-[10px] font-bold uppercase tracking-[0.16em] text-natural-sage">Choose a rhythm</p><div className="mt-4 space-y-3">{deep.map((item) => <button key={item.id} disabled={!billing?.enabled || active} onClick={() => setSku(item.id)} className="w-full rounded-2xl border border-natural-border bg-white/60 p-4 text-left outline-none transition hover:border-natural-sage/40 focus-visible:ring-2 focus-visible:ring-natural-sage/50 disabled:cursor-default disabled:opacity-70"><div className="flex items-baseline justify-between gap-3"><span className="text-sm font-bold text-natural-dark">{item.period === "year" ? "Yearly" : "Monthly"}</span><span className="text-lg font-bold text-natural-dark">{formatVnd(item.amountVnd)}</span></div><p className="mt-1 text-xs text-natural-stone">{item.period === "year" ? `A full year of deeper reading${saving ? ` · save ${formatVnd(saving)}` : ""}` : "A month to read more closely"}</p></button>)}</div>{billing?.enabled ? <p className="mt-4 text-xs leading-relaxed text-natural-stone">Choose a rhythm to receive an order-specific MB QR and transfer reference.</p> : <p className="mt-4 rounded-2xl bg-natural-sage/5 p-3 text-xs leading-relaxed text-natural-stone">Checkout is being prepared. Nothing changes to your current reading experience.</p>}</aside></section>
      <section className="rounded-3xl border border-natural-border bg-natural-cream p-5 shadow-sm sm:p-7"><div className="max-w-2xl"><p className="font-sans text-[10px] font-bold uppercase tracking-[0.16em] text-natural-sage">Current monthly capacity</p><h2 className="mt-1 text-2xl font-bold text-natural-dark">Enough room to follow a real reading life.</h2><p className="mt-2 text-sm leading-relaxed text-natural-stone">Deep Reader capacity resets by app month. It is a calm boundary around the companion—not a score to chase.</p></div><div className="mt-5 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{["20 Book Wiki or Reading Lens analyses", "10 chapter podcasts", "4 recap podcasts", "1 monthly reading review", "30 Ask My Reading questions", "12 cross-book connection requests"].map((label) => <div key={label} className="rounded-2xl border border-natural-border bg-white/55 px-4 py-3 font-sans text-sm font-medium text-natural-dark">{label}</div>)}</div></section>
      <PricingComparison billingEnabled={Boolean(billing?.enabled)} activeTier={entitlement?.subscription.tier || "free"} onChoose={(selectedSku) => setSku(selectedSku)} />
      <section className="rounded-3xl border border-natural-border bg-natural-cream p-5 shadow-sm sm:p-7" aria-labelledby="payment-heading"><div className="max-w-2xl"><p className="font-sans text-[10px] font-bold uppercase tracking-[0.16em] text-natural-sage">Payment, without surprises</p><h2 id="payment-heading" className="mt-1 text-2xl font-bold text-natural-dark">A clear transfer, matched to one order.</h2></div><div className="mt-6 grid gap-3 md:grid-cols-3">{[["1", "Choose your rhythm", "Select a plan only when checkout is open. Each paid tier has its own order and transfer reference."], ["2", "Receive a unique reference", "Use the exact payment QR, amount and transfer reference shown for your order."], ["3", "Access is applied carefully", "Payment is reviewed through the internal process before membership access is applied."]].map(([number, title, copy]) => <div key={number} className="rounded-2xl border border-natural-border bg-white/55 p-4"><span className="inline-flex h-6 w-6 items-center justify-center rounded-full bg-natural-sage font-sans text-xs font-bold text-white">{number}</span><h3 className="mt-3 text-sm font-bold text-natural-dark">{title}</h3><p className="mt-1 text-xs leading-relaxed text-natural-stone">{copy}</p></div>)}</div><div className="mt-5 flex items-start gap-2 rounded-2xl bg-natural-sage/5 p-4 text-xs leading-relaxed text-natural-stone"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-natural-sage" /><p>Chapter does not store card details. Keep the transfer reference unchanged; your Account keeps payment history and order status.</p></div></section>
      <PricingFaq />
      <section className="rounded-3xl bg-natural-dark px-5 py-7 text-center text-natural-cream sm:px-8"><h2 className="text-2xl font-bold">Read at your pace. Keep more of what stays.</h2><p className="mx-auto mt-2 max-w-xl text-sm leading-relaxed text-natural-cream/70">Deep Reader is there when a book deserves a longer conversation.</p>{billing?.enabled && monthly && !active ? <button onClick={() => setSku(monthly.id)} className="mt-5 min-h-11 rounded-full bg-natural-cream px-5 font-sans text-xs font-bold text-natural-dark">Explore Deep Reader</button> : <p className="mt-5 font-sans text-xs text-natural-cream/70">{active ? "You already have Deep Reader access." : "Checkout is being prepared."}</p>}</section>
    </>}{sku && <VietQrCheckoutSheet sku={sku} onClose={() => setSku(null)} />}</main>;
}
