import React from "react";
import type { ReferenceCardDraft, ReferenceCardFields, ReferenceCardType } from "../../types";

const empty = (type: ReferenceCardType): ReferenceCardFields => type === "recipe" ? { servings: null, ingredients: [], steps: [], nutrition: [], substitutions: [] } : type === "formula" ? { expression: "", variables: [], conditions: [], steps: [], example: null } : { prerequisites: [], steps: [], checklist: [], expectedOutcome: null };
const lines = (value: string[]) => value.join("\n");
const toLines = (value: string) => value.split("\n").map((row) => row.trim()).filter(Boolean);
const input = "mt-1 min-h-11 w-full rounded-xl border border-natural-border bg-natural-bg px-3 py-2 text-sm text-natural-dark focus:outline-none focus:ring-2 focus:ring-natural-sage";

export function resetFieldsFor(type: ReferenceCardType) { return empty(type); }
export default function ReferenceCardFieldsEditor({ draft, onChange }: { draft: ReferenceCardDraft; onChange: (next: ReferenceCardDraft) => void }) {
 const update = (fields: ReferenceCardFields) => onChange({ ...draft, fields });
 if (draft.cardType === "recipe") { const f = draft.fields as any; return <div className="space-y-3"><label className="block text-xs font-bold text-natural-stone">Servings<input className={input} value={f.servings || ""} onChange={e => update({ ...f, servings: e.target.value || null })} /></label><label className="block text-xs font-bold text-natural-stone">Ingredients <span className="font-normal">(one per line; amount — item)</span><textarea className={input} rows={4} value={f.ingredients.map((i: any) => `${i.amount || ""}${i.amount ? " — " : ""}${i.item}`).join("\n")} onChange={e => update({ ...f, ingredients: toLines(e.target.value).map(row => { const [amount, ...rest] = row.split("—"); return rest.length ? { amount: amount.trim() || null, item: rest.join("—").trim() } : { amount: null, item: amount }; }) })} /></label><List label="Steps" value={f.steps} onChange={v => update({ ...f, steps: v })}/><List label="Nutrition" value={f.nutrition} onChange={v => update({ ...f, nutrition: v })}/><List label="Substitutions" value={f.substitutions} onChange={v => update({ ...f, substitutions: v })}/></div>; }
 if (draft.cardType === "formula") { const f = draft.fields as any; return <div className="space-y-3"><label className="block text-xs font-bold text-natural-stone">Expression<input className={input} value={f.expression} onChange={e => update({ ...f, expression: e.target.value })}/></label><label className="block text-xs font-bold text-natural-stone">Variables <span className="font-normal">(symbol — meaning — unit)</span><textarea className={input} rows={3} value={f.variables.map((v:any)=>[v.symbol,v.meaning,v.unit].filter(Boolean).join(" — ")).join("\n")} onChange={e => update({...f,variables:toLines(e.target.value).map(row=>{const [symbol,meaning,unit]=row.split("—").map(x=>x.trim());return {symbol:symbol||"",meaning:meaning||"",unit:unit||null};})})}/></label><List label="Conditions" value={f.conditions} onChange={v=>update({...f,conditions:v})}/><List label="Steps" value={f.steps} onChange={v=>update({...f,steps:v})}/><label className="block text-xs font-bold text-natural-stone">Example<textarea className={input} rows={2} value={f.example || ""} onChange={e=>update({...f,example:e.target.value||null})}/></label></div>; }
 const f = draft.fields as any; return <div className="space-y-3"><List label="Prerequisites" value={f.prerequisites} onChange={v=>update({...f,prerequisites:v})}/><List label="Steps" value={f.steps} onChange={v=>update({...f,steps:v})}/><List label="Checklist" value={f.checklist} onChange={v=>update({...f,checklist:v})}/><label className="block text-xs font-bold text-natural-stone">Expected outcome<textarea className={input} rows={2} value={f.expectedOutcome || ""} onChange={e=>update({...f,expectedOutcome:e.target.value||null})}/></label></div>;
}
function List({label,value,onChange}:{label:string;value:string[];onChange:(v:string[])=>void}) { return <label className="block text-xs font-bold text-natural-stone">{label}<textarea className={input} rows={3} value={lines(value)} onChange={e=>onChange(toLines(e.target.value))}/></label>; }
