import React, { useState } from "react";
import { ChevronDown, ChevronRight } from "lucide-react";
import { GlossaryLabel } from "./ContextualGlossary";
export interface MindMapNode { text?: string; insight?: string; evidence?: string; page?: number | string; status?: string; }
export interface MindMapData { root?: string; thesis?: string; branches?: { theme?: string; color?: string; nodes?: (string | MindMapNode)[]; status?: string; evidence?: string; page?: number | string }[]; }
const text = (value: unknown) => typeof value === "string" ? value : "";
const statusTerm = (value: string) => { const normalized = value.toLowerCase(); const match = (["Deepened", "Shifted", "Introduced", "Resolved", "Uncertain", "Implied"] as const).find(key => normalized.includes(key.toLowerCase())); return match || null; };
export default function MindMap({ data, bookTitle }: { data: MindMapData; bookTitle: string }) {
  const [open, setOpen] = useState<number | null>(0);
  const branches = Array.isArray(data?.branches) ? data.branches : [];
  const thesis = text(data?.thesis) || text(data?.root) || "A thesis will appear as more reading is saved.";
  return <section aria-labelledby="knowledge-map-thesis" className="space-y-4">
    <header className="rounded-2xl border border-natural-sage/25 bg-natural-sage/5 p-4 sm:p-5"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-natural-sage">{bookTitle}</p><h4 id="knowledge-map-thesis" className="mt-2 text-base font-bold leading-snug text-natural-dark">{thesis}</h4><p className="mt-2 text-[11px] leading-relaxed text-natural-stone">A thesis-first view of the ideas recorded in your reading sessions.</p></header>
    {branches.length ? <div className="grid gap-3 md:grid-cols-2">{branches.map((branch, index) => { const expanded = open === index; const nodes = Array.isArray(branch.nodes) ? branch.nodes : []; const state = text(branch.status); const stateTerm = statusTerm(state); return <article key={`${text(branch.theme)}-${index}`} className="overflow-hidden rounded-2xl border border-natural-border bg-white/55"><button type="button" aria-expanded={expanded} onClick={() => setOpen(expanded ? null : index)} className="flex min-h-14 w-full items-center gap-3 px-4 text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-natural-sage/50"><span className="h-3 w-3 shrink-0 rounded-full" style={{ backgroundColor: branch.color || "#8caa8b" }} /><span className="flex-1"><strong className="block text-sm text-natural-dark">{text(branch.theme) || `Theme ${index + 1}`}</strong>{stateTerm ? <span className="text-[10px] text-natural-sage"><GlossaryLabel term={stateTerm} /></span> : state && <span className="text-[10px] text-natural-stone">{state}</span>}</span>{expanded ? <ChevronDown className="h-4 w-4 text-natural-stone" /> : <ChevronRight className="h-4 w-4 text-natural-stone" />}</button>{expanded && <div className="space-y-3 border-t border-natural-border px-4 py-3">{nodes.length ? nodes.map((raw, nodeIndex) => { const node = typeof raw === "string" ? { text: raw } : raw || {}; const label = text(node.text) || text(node.insight) || "Recorded idea"; return <div key={nodeIndex} className="border-l-2 border-natural-sage/35 pl-3"><p className="text-xs leading-relaxed text-natural-dark">{label}</p>{text(node.evidence) && <p className="mt-1 text-[11px] leading-relaxed text-natural-stone"><GlossaryLabel term="Evidence" />: {node.evidence}</p>}{node.page != null && <p className="mt-1 text-[10px] font-semibold text-natural-sage">Page {String(node.page)}</p>}</div>; }) : <p className="text-[11px] text-natural-stone">No recorded ideas are available yet.</p>}{text(branch.evidence) && <p className="border-t border-natural-border pt-2 text-[11px] text-natural-stone"><GlossaryLabel term="Evidence" />: {branch.evidence}{branch.page != null && ` · Page ${String(branch.page)}`}</p>}</div>}</article>; })}</div> : <div className="rounded-2xl border border-dashed border-natural-border p-5 text-center text-xs text-natural-stone">The map will take shape as saved reading gives it grounded material.</div>}
  </section>;
}
