import { FormEvent, useState } from "react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import { useAuth } from "../AuthContext";

export default function ResetPassword() {
  const { completePasswordReset } = useAuth(); const [params] = useSearchParams(); const navigate = useNavigate();
  const token = params.get("token") || ""; const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); if (password !== confirm) return setError("Passwords do not match."); setBusy(true); try { await completePasswordReset(token, password, confirm); navigate("/", { replace: true }); } catch { setPassword(""); setConfirm(""); setError("This reset link is invalid, expired, or has already been used."); } finally { setBusy(false); } }
  return <main className="min-h-screen bg-natural-bg p-4 font-sans"><section className="mx-auto mt-[12vh] w-full max-w-sm rounded-[28px] border border-natural-border bg-natural-cream p-7 shadow-sm"><p className="text-xs font-bold uppercase tracking-widest text-natural-sage">Chapter</p><h1 className="mt-2 font-sans text-2xl font-bold text-natural-dark">Choose a new password</h1>{!token ? <div className="mt-4 space-y-3 text-sm text-natural-stone"><p>This reset link is incomplete.</p><Link className="font-bold text-natural-sage underline" to="/forgot-password">Request a new link</Link></div> : <form onSubmit={submit} className="mt-5 space-y-4"><p className="text-sm text-natural-stone">Use at least 10 characters.</p><label className="block text-xs font-bold">New password<input required minLength={10} type="password" value={password} onChange={(e) => setPassword(e.target.value)} className="mt-1.5 min-h-11 w-full rounded-xl border border-natural-border bg-natural-bg px-3 text-sm outline-none focus:border-natural-sage focus:ring-2 focus:ring-natural-sage/20" /></label><label className="block text-xs font-bold">Confirm password<input required minLength={10} type="password" value={confirm} onChange={(e) => setConfirm(e.target.value)} className="mt-1.5 min-h-11 w-full rounded-xl border border-natural-border bg-natural-bg px-3 text-sm outline-none focus:border-natural-sage focus:ring-2 focus:ring-natural-sage/20" /></label>{error && <p role="alert" className="text-xs text-red-700">{error}</p>}<button disabled={busy} className="min-h-11 w-full rounded-full bg-natural-sage text-xs font-bold uppercase tracking-wider text-white disabled:opacity-60">{busy ? "Saving…" : "Reset password"}</button></form>}</section></main>;
}
