import { FormEvent, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { BookMarked, Loader2 } from "lucide-react";
import { useAuth } from "../AuthContext";

export default function Signup() {
  const { signup } = useAuth(); const [params] = useSearchParams();
  const [email, setEmail] = useState(""); const [displayName, setDisplayName] = useState(""); const [password, setPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); if (password !== confirmPassword) return setError("Passwords do not match."); setSubmitting(true); try { await signup(email, displayName, password, confirmPassword); } catch (cause: any) { setError(cause?.message || "We could not create your account. Please try again."); } finally { setSubmitting(false); } }
  const inputClass = "mt-1.5 w-full rounded-xl border border-natural-border bg-natural-bg px-3 py-2.5 text-natural-dark placeholder:text-natural-stone/70 outline-none transition focus:border-natural-sage focus:ring-2 focus:ring-natural-sage/35 dark:bg-natural-cream/15 dark:[color-scheme:dark]";
  return <main className="min-h-screen bg-natural-bg flex items-center justify-center p-4 font-sans"><form onSubmit={submit} className="w-full max-w-sm bg-natural-cream border border-natural-border rounded-[28px] p-7 shadow-sm space-y-4"><div className="text-center space-y-2"><div className="mx-auto w-10 h-10 bg-natural-sage rounded-full text-white flex items-center justify-center"><BookMarked className="w-5 h-5" /></div><h1 className="font-bold text-xl text-natural-dark">Create your Chapter</h1><p className="text-xs text-natural-stone">Start a quieter reading practice.</p></div><label className="block text-xs font-bold text-natural-dark">Email<input required autoFocus type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@example.com" className={inputClass} /></label><label className="block text-xs font-bold text-natural-dark">Your name<input required value={displayName} onChange={(e) => setDisplayName(e.target.value)} placeholder="How should Chapter greet you?" className={inputClass} /></label><label className="block text-xs font-bold text-natural-dark">Password<input required minLength={10} type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="At least 10 characters" className={inputClass} /></label><label className="block text-xs font-bold text-natural-dark">Confirm password<input required minLength={10} type="password" value={confirmPassword} onChange={(e) => setConfirmPassword(e.target.value)} className={inputClass} /></label>{params.get("auth_error") === "google" && <p role="alert" className="text-xs text-red-600">Google sign-up could not be completed. Please try again.</p>}{error && <p role="alert" className="text-xs text-red-600">{error}</p>}<button disabled={submitting} className="w-full rounded-full bg-natural-sage py-2.5 text-xs font-bold uppercase tracking-wider text-white disabled:opacity-60">{submitting ? <Loader2 className="mx-auto w-4 h-4 animate-spin" /> : "Create account"}</button><div className="flex items-center gap-3 text-[10px] font-bold uppercase tracking-widest text-natural-stone"><span className="h-px flex-1 bg-natural-border" />or<span className="h-px flex-1 bg-natural-border" /></div><button type="button" onClick={() => window.location.assign("/api/auth/google?intent=signup")} className="min-h-11 w-full rounded-full border border-natural-border bg-natural-bg text-xs font-bold text-natural-dark hover:border-natural-sage/60">Continue with Google to sign up</button><p className="text-center text-xs text-natural-stone">Already have an account? <Link to="/login" className="font-bold text-natural-sage underline">Sign in</Link></p></form></main>;
}
