import { useEffect, useState } from "react";
import { Copy, Loader2, X } from "lucide-react";
import { api, type BillingOrder } from "../api";

export default function VietQrCheckoutSheet({ sku, onClose }: { sku:string; onClose:()=>void }) {
  const [order, setOrder] = useState<BillingOrder | null>(null); const [error, setError] = useState("");
  useEffect(()=>{ void api.createBillingOrder(sku, `checkout:${sku}:${crypto.randomUUID()}`).then(x=>setOrder(x.order)).catch(()=>setError("Bank-transfer checkout is unavailable right now.")); },[sku]);
  const copy=async(v:string)=>{ await navigator.clipboard?.writeText(v); };
  return <div role="dialog" aria-modal="true" className="fixed inset-0 z-50 flex items-end justify-center bg-natural-dark/35 p-3 sm:items-center"><section className="w-full max-w-md rounded-3xl bg-natural-cream p-5 shadow-xl sm:p-6"><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-[10px] font-bold uppercase tracking-[.16em] text-natural-sage">Bank transfer</p><h2 className="mt-1 text-xl font-bold text-natural-dark">Confirm your reading plan</h2></div><button onClick={onClose} aria-label="Close checkout" className="min-h-11 min-w-11 rounded-full text-natural-stone"><X className="mx-auto h-5 w-5" /></button></div>{!order&&!error&&<div className="flex min-h-48 items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-natural-sage" /></div>}{error&&<p className="mt-5 rounded-2xl bg-white p-4 text-sm text-natural-stone">{error}</p>}{order&&<div className="mt-5 space-y-4"><img src={order.qrUrl || undefined} alt="Payment QR code" className="mx-auto w-56 max-w-full rounded-2xl border border-natural-border bg-white p-2"/><div className="rounded-2xl bg-white/70 p-4 text-sm text-natural-dark"><p className="font-bold">{new Intl.NumberFormat("vi-VN").format(order.amountVnd)} VNĐ</p><p className="mt-1 text-xs text-natural-stone">Transfer content</p><button onClick={()=>void copy(order.transferReference)} className="mt-1 flex min-h-11 w-full items-center justify-between gap-3 rounded-xl border border-natural-border px-3 font-mono text-xs"><span>{order.transferReference}</span><Copy className="h-4 w-4" /></button></div><p className="text-xs leading-relaxed text-natural-stone">Your plan activates after we match the transfer. Please use the exact transfer reference and amount and keep this page open or check Account later.</p></div>}</section></div>;
}