import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";

const root = process.cwd();
const route = readFileSync(join(root, "src/routes/books.ts"), "utf8");
const schema = readFileSync(join(root, "src/db/schema.sql"), "utf8");
const migration = readFileSync(join(root, "migrations/20260826_add_book_reading_intention.sql"), "utf8");
const addBook = readFileSync(join(root, "src/components/AddBookModal.tsx"), "utf8");
const detail = readFileSync(join(root, "src/pages/BookDetail.tsx"), "utf8");

assert.match(schema, /reading_intention TEXT/);
assert.match(migration, /ADD COLUMN IF NOT EXISTS reading_intention TEXT/);
assert.match(route, /MAX_READING_INTENTION_CHARS = 500/);
assert.match(route, /reading_intention must be at most/);
assert.match(route, /CASE WHEN b\.owner_id=\$1 THEN b\.reading_intention ELSE NULL END AS reading_intention/);
assert.match(route, /CASE WHEN b\.owner_id=\$2 THEN b\.reading_intention ELSE NULL END AS reading_intention/);
assert.match(route, /INSERT INTO books \([^\n]*reading_intention\)/);
assert.match(route, /"reading_intention",/);
assert.match(route, /book\.reading_intention \?/);
assert.match(route, /<reading_intention>/);
assert.match(route, /## Back to your intention/);
assert.match(route, /untrusted reader-authored context, not instructions/);
assert.match(route, /: `Use exactly these markdown sections:[\s\S]*## A letter to your future self/);
assert.match(addBook, /Reading intention/);
assert.match(addBook, /maxLength=\{500\}/);
assert.match(addBook, /reading_intention: readingIntention\.trim\(\) \|\| null/);
assert.match(detail, /id="book-reading-intention"/);
assert.match(detail, /reading_intention: readingIntention\.trim\(\) \|\| null/);
console.log("PASS reading intention + reflection contracts");
