import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { aggregateCharacterStorylines, boundStoryThreadSource, buildStoryThreadPrompt, mergeStoryState, parseStoryThreadAnalysis, STORY_THREAD_MAX_SOURCE_CHARS, storyCompatSummary } from "../src/storyThread.js";

const raw = JSON.stringify({ storyRecap: "Mara accepts the sealed letter and leaves before dawn.", changedEvents: ["Mara accepts the sealed letter."], threads: [{ id: "sealed-letter", label: "The sealed letter", status: "escalating", detail: "Mara now carries it." }], characterPulse: [{ name: "Mara", pulse: "She acts despite uncertainty." }], characterArcs: [{ name: "Mara", development: "She chooses to carry the sealed letter." }], characterRelationships: [{ people: ["Mara", "Tomas"], detail: "Tomas entrusts Mara with the letter." }], readerMemory: ["Mara is carrying a sealed letter."], confidenceNotes: [] });
const analysis = parseStoryThreadAnalysis(`\`\`\`json\n${raw}\n\`\`\``);
assert.equal(analysis.threads[0].status, "escalating"); assert.equal(analysis.characterArcs[0].name, "Mara"); assert.equal(storyCompatSummary(analysis).quote, null); assert.throws(() => parseStoryThreadAnalysis('{"storyRecap":"missing required fields"}'));
const legacy = parseStoryThreadAnalysis(JSON.stringify({ ...JSON.parse(raw), characterArcs: undefined, characterRelationships: undefined })); assert.deepEqual(legacy.characterArcs, []); assert.deepEqual(legacy.characterRelationships, []);
const firstState = mergeStoryState({ threads: [{ id: "sealed-letter", label: "Old", status: "open", detail: "Old detail" }], characterPulse: [], readerMemory: [] }, analysis); assert.equal(firstState.threads[0].status, "escalating");
const followUp = parseStoryThreadAnalysis(JSON.stringify({ ...JSON.parse(raw), storyRecap: "Mara hides the letter.", characterPulse: [{ name: "MARA", pulse: "She becomes more guarded." }], characterArcs: [{ name: "Mara", development: "She becomes more guarded while hiding the letter." }], characterRelationships: [{ people: ["Mara", "Tomas"], detail: "Their trust is strained by the concealment." }], readerMemory: ["The watchman has noticed Mara."] }));
const secondState = mergeStoryState(firstState, followUp); assert.equal(secondState.characterPulse.find((character) => character.name.toLowerCase() === "mara")?.pulse, "She becomes more guarded.");
const aggregate = aggregateCharacterStorylines([{ log_id: "one", session: 1, page_start: 1, page_end: 4, analysis }, { log_id: "two", session: 2, page_start: 5, page_end: 9, analysis: followUp }]); assert.equal(aggregate.characters[0].developments.length, 2); assert.equal(aggregate.relationships[0].moments.length, 2); assert.equal(aggregate.lastCitation?.pageEnd, 9);
const prompt = buildStoryThreadPrompt({ title: "Test", author: "Author", start: 1, end: 2, total: 10, lang: "en", sourceText: "Mara accepts the sealed letter.", priorState: secondState }); assert.match(prompt.system, /characterRelationships/); assert.match(prompt.system, /CURRENT READING TEXT/); assert.match(prompt.user, /Current reading text/);
const boundedSource = boundStoryThreadSource("A".repeat(STORY_THREAD_MAX_SOURCE_CHARS + 5000)); assert.ok(boundedSource.includes("Middle of this reading range omitted"));
const routeSource = readFileSync(new URL("../src/routes/books.ts", import.meta.url), "utf8"); const serverSource = readFileSync(new URL("../server.ts", import.meta.url), "utf8"); const storyThreadSource = readFileSync(new URL("../src/storyThread.ts", import.meta.url), "utf8"); const storyViewSource = readFileSync(new URL("../src/components/story/StoryThreadView.tsx", import.meta.url), "utf8"); const detailSource = readFileSync(new URL("../src/pages/BookDetail.tsx", import.meta.url), "utf8");
assert.match(routeSource, /listStoryThreadAnalyses\(id, readingRound\)/); assert.match(routeSource, /reading_experience='analytical'/); assert.match(routeSource, /Story Thread books do not use Reading Lens/); assert.match(serverSource, /Story Thread books do not use Knowledge Maps/); assert.match(storyThreadSource, /aggregateCharacterStorylines/); assert.match(storyThreadSource, /characterRelationships/); assert.match(storyViewSource, /Character Storylines/); assert.match(storyViewSource, /Relationship timeline/); assert.match(storyViewSource, /Nothing beyond this reading round is shown/); assert.match(storyViewSource, /min-h-11/); assert.match(storyViewSource, /aggregateCharacterStorylines\(analyses\)/); assert.match(detailSource, /<StoryThreadView[\s\S]*?summaryLang=\{book\.summary_lang\}/);
console.log("STORY_THREAD_FIXTURES_OK");
