import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { extractJson } from "../src/llmJson.js";
import { buildJourneySynthesisPrompt, parseJourneySynthesis, type JourneySource } from "../src/journeySynthesis.js";
const ref={logId:"11111111-1111-4111-8111-111111111111",session:1};
const sources:JourneySource[]=[{...ref,analystSummary:"summary",coreArgument:"argument",argumentMap:[],keyConcepts:[],assumptionsAndLimits:[],questionsToCarryForward:[],durableInsights:[],quote:"verbatim quote",confidenceNotes:[]}];
const valid={throughLine:"A grounded through line.",evolvingConcepts:[{term:"Care",trajectory:"It develops.",firstSession:ref,lastSession:ref}],resolvedQuestions:[],openQuestions:["What follows?"],tensions:[],confidenceNotes:[],outputLanguage:"en"};
assert.equal(parseJourneySynthesis(JSON.stringify(valid),null,[ref]).throughLine,valid.throughLine);
assert.equal((extractJson("```json\n"+JSON.stringify(valid)+"\n```") as any).throughLine,valid.throughLine);
assert.throws(()=>parseJourneySynthesis("{",null,[ref]));
assert.throws(()=>parseJourneySynthesis(JSON.stringify({...valid,evolvingConcepts:[{...valid.evolvingConcepts[0],firstSession:{logId:"bad",session:1}}]}),null,[ref]));
const prompt=buildJourneySynthesisPrompt({priorSynthesis:null,sources,language:"en"});
for(const key of ["prior synthesis","coreArgument","argumentMap","keyConcepts","assumptionsAndLimits","questionsToCarryForward","durableInsights","quote","confidenceNotes","logId"]) assert.match(prompt.toLowerCase(),new RegExp(key.toLowerCase()));
const migration=readFileSync(new URL("../migrations/20260802_add_reading_lens_synthesis.sql",import.meta.url),"utf8"); const schema=readFileSync(new URL("../src/db/schema.sql",import.meta.url),"utf8"); const repo=readFileSync(new URL("../src/readingLensSynthesisRepository.ts",import.meta.url),"utf8"); const route=readFileSync(new URL("../src/routes/books.ts",import.meta.url),"utf8");
for(const source of [migration,schema]) for(const fragment of ["reading_lens_synthesis","book_id UUID PRIMARY KEY","through_line","last_log_id","last_log_date","last_log_session","source_revision","stale BOOLEAN"]) assert.match(source,new RegExp(fragment));
assert.match(repo,/GREATEST/); assert.match(repo,/markReadingLensSynthesisStaleIfCovered/); assert.match(repo,/\(l.date,l.session,l.id\) <=/); assert.match(route,/callJsonLLM/); assert.ok(route.includes('booksRouter.get("/:id/reading-lens/synthesis"'));
const post=route.slice(route.indexOf('booksRouter.post("/:id/reading-lens/synthesis"'),route.indexOf("// ── B6:")); assert.doesNotMatch(post,/slice\(-24\)/); assert.match(post,/usableWatermark/); assert.match(post,/quote:r.analysis\?\.quote/); assert.doesNotMatch(post,/callLLM\(/);
const card=readFileSync(new URL("../src/components/JourneySynthesisCard.tsx",import.meta.url),"utf8"); const detail=readFileSync(new URL("../src/pages/BookDetail.tsx",import.meta.url),"utf8"); const journey=readFileSync(new URL("../src/components/JourneyView.tsx",import.meta.url),"utf8");
assert.match(card,/reading-lens-synthesis/); assert.match(card,/stale/); assert.match(card,/Synthesize this journey/); assert.match(detail,/getJourneySynthesis/); assert.match(detail,/synthesizeJourney/); assert.match(detail,/JourneySynthesisCard/); assert.match(journey,/reading-lens-journey/); assert.match(journey,/scrollIntoView/);
console.log("JOURNEY_SYNTHESIS_FIXTURES_OK");
