import crypto from "crypto";
import { withTransaction, query } from "../db.js";
import { bestEffortTouchLastActive } from "../userLifecycleTracking.js";
import { billingSku } from "./catalog.js";
import { newTransferReference, vietQrConfig, vietQrUrl } from "./vietqr.js";

type Order = any;
function expose(r: any) {
  const cfg = vietQrConfig();
  let qrUrl: string | null = null;
  if (r.status === "pending" && cfg.enabled) {
    try { qrUrl = vietQrUrl({ ...cfg, amountVnd: Number(r.amount_vnd), transferReference: r.transfer_reference }); }
    catch { /* disabled or incomplete config: history remains readable */ }
  }
  return { id:r.id, sku:r.sku, tier:r.tier, period:r.billing_period, amountVnd:Number(r.amount_vnd), currency:r.currency, status:r.status, transferReference:r.transfer_reference, expiresAt:r.expires_at, createdAt:r.created_at, qrUrl };
}
export async function expireBillingOrders() { await query("UPDATE billing_orders SET status='expired',updated_at=now() WHERE status='pending' AND expires_at<=now()"); }
export async function createBillingOrder(ownerId:string, skuInput:unknown, requestKey:unknown) { const cfg=vietQrConfig(); if(!cfg.enabled) return { status:"unavailable" as const, order:null }; try { vietQrUrl({ ...cfg, amountVnd: 1, transferReference: "CHP-A1B2C3D4E5F6" }); } catch { return { status:"unavailable" as const, order:null }; } const sku=billingSku(skuInput); const key=typeof requestKey==="string"?requestKey.trim():""; if(!sku||!key||key.length>160) throw new Error("invalid checkout request"); await expireBillingOrders(); const prior=(await query<Order>("SELECT * FROM billing_orders WHERE owner_id=$1 AND request_key=$2",[ownerId,key])).rows[0]; if(prior) return {status:"existing" as const,order:expose(prior)}; for(let n=0;n<4;n++){try{const ref=newTransferReference();const r=(await query<Order>("INSERT INTO billing_orders(owner_id,request_key,transfer_reference,provider,sku,tier,billing_period,amount_vnd,expires_at) VALUES($1,$2,$3,'vietqr_static',$4,$5,$6,$7,now()+($8::text||' minutes')::interval) RETURNING *",[ownerId,key,ref,sku.id,sku.tier,sku.period,sku.amountVnd,cfg.expiryMinutes])).rows[0];return {status:"created" as const,order:expose(r)};}catch(e:any){if(e?.code!=="23505")throw e;}} throw new Error("could not create transfer reference"); }
export async function getBillingOrder(ownerId:string,id:string){await expireBillingOrders();const r=(await query<Order>("SELECT * FROM billing_orders WHERE id=$1 AND owner_id=$2",[id,ownerId])).rows[0];return r?expose(r):null;}
export async function billingMe(ownerId:string){await expireBillingOrders();const [orders,tx]=(await Promise.all([query<Order>("SELECT * FROM billing_orders WHERE owner_id=$1 ORDER BY created_at DESC LIMIT 20",[ownerId]),query<any>("SELECT t.*,o.sku,o.transfer_reference FROM billing_transactions t JOIN billing_orders o ON o.id=t.order_id WHERE t.owner_id=$1 ORDER BY t.created_at DESC LIMIT 20",[ownerId])]));return {orders:orders.rows.map(expose),transactions:tx.rows.map(r=>({id:r.id,orderId:r.order_id,sku:r.sku,amountVnd:Number(r.amount_vnd),currency:r.currency,periodStart:r.period_start,periodEnd:r.period_end,createdAt:r.created_at}))};}
export async function confirmPaidOrder(input:{orderId:string;confirmerId:string;receiptReference:string;amountVnd:number}){const result=await withTransaction(async c=>{const r=(await c.query("SELECT * FROM billing_orders WHERE id=$1 FOR UPDATE",[input.orderId])).rows[0];if(!r)throw new Error("order not found");if(r.status==="paid")return {status:"existing" as const,order:expose(r)};if(r.status!=="pending"||new Date(r.expires_at)<=new Date())throw new Error("order is not payable");if(!Number.isInteger(input.amountVnd)||input.amountVnd!==Number(r.amount_vnd)||!input.receiptReference.trim())throw new Error("payment amount or receipt reference does not match");const old=(await c.query("SELECT tier,current_period_end FROM subscriptions WHERE user_id=$1 FOR UPDATE",[r.owner_id])).rows[0];const activeOld=Boolean(old?.current_period_end&&new Date(old.current_period_end)>new Date());const base=activeOld?new Date(old.current_period_end):new Date();const end=new Date(base);end.setUTCMonth(end.getUTCMonth()+(r.billing_period==="year"?12:1));const tierRank:Record<string,number>={free:0,plus:1,deep_reader:2};const effectiveTier=activeOld&&(tierRank[old.tier]??0)>(tierRank[r.tier]??0)?old.tier:r.tier;await c.query("INSERT INTO billing_confirmations(order_id,confirmer_id,receipt_reference,received_amount_vnd) VALUES($1,$2,$3,$4)",[r.id,input.confirmerId,input.receiptReference.trim(),input.amountVnd]);await c.query("INSERT INTO billing_transactions(owner_id,order_id,amount_vnd,provider,period_start,period_end) VALUES($1,$2,$3,'vietqr_static',$4,$5)",[r.owner_id,r.id,input.amountVnd,base,end]);await c.query("INSERT INTO subscriptions(user_id,tier,status,current_period_end,provider,granted_by,metadata) VALUES($1,$2,'active',$3,'vietqr_static','payment',$4) ON CONFLICT(user_id) DO UPDATE SET tier=EXCLUDED.tier,status='active',current_period_end=EXCLUDED.current_period_end,provider='vietqr_static',granted_by='payment',updated_at=now()",[r.owner_id,effectiveTier,end,JSON.stringify({billingOrderId:r.id})]);const saved=(await c.query("UPDATE billing_orders SET status='paid',paid_at=now(),updated_at=now() WHERE id=$1 RETURNING *",[r.id])).rows[0];return {status:"confirmed" as const,order:expose(saved),ownerId:r.owner_id};}); if(result.status==="confirmed") bestEffortTouchLastActive(result.ownerId); const {ownerId,...publicResult}=result as any; return publicResult;}
export function billingServiceFixtureCheck(){if(!/^CHP-[A-F0-9]{12}$/.test(newTransferReference()))throw new Error("reference fixture failed");}
if(process.env.RUN_BILLING_SERVICE_FIXTURE==="1"){billingServiceFixtureCheck();console.log("BILLING_SERVICE_FIXTURES_OK");}
