import { query } from "./db.js";
import { callJsonLLM } from "./llm.js";
import { consumeUsage, releaseUsage, reserveUsage } from "./usage.js";
import { FeatureUnavailableError, QuotaExceededError } from "./entitlements.js";
export const ASK_READING_SCHEMA_VERSION=1;
export type AskSource={sourceType:string;sourceId:string;bookId:string;bookTitle:string;occurredAt:string;content:string};
export type AskAnswer={id:string;requestKey:string;question:string;outputLanguage:"vi"|"en";answer:string;sourceRefs:Array<{sourceType:string;sourceId:string;bookTitle:string;occurredAt:string}>;sourceCount:number;createdAt:string};
const clean=(v:unknown,n:number)=>typeof v==='string'?v.trim().slice(0,n):'';
export function normalizeQuestion(v:unknown){const q=clean(v,500);if(q.length<3||q.length>500)throw new Error('question must be between 3 and 500 characters');return q;}
export function resolveOutputLanguage(q:string, sources:AskSource[]):"vi"|"en"{return /[ăâđêôơưáàảãạĂÂĐÊÔƠƯÁÀẢÃẠ]/.test(q+' '+sources.map(s=>s.content).join(' '))?'vi':'en';}
export function hasRelevantSource(sources:AskSource[]){return sources.length>0;}
export function buildAskReadingPrompt(question:string,language:"vi"|"en",sources:AskSource[]){const material=sources.map(s=>`[${s.sourceType}:${s.sourceId}] ${s.bookTitle} (${s.occurredAt})\n${s.content}`).join('\n\n').slice(0,50000);return `Answer the reader's question using only the saved reading evidence below. Write entirely in ${language==='vi'?'Vietnamese':'English'}. If evidence is insufficient, say so clearly; do not invent. Return ONLY JSON: {"answer":"...","sourceRefs":[{"sourceType":"...","sourceId":"..."}]}. Keep answer under 1800 characters and sourceRefs limited to supplied IDs. Question: ${question}\n\nEVIDENCE\n${material}`;}
export function parseAskReading(raw:string,language:"vi"|"en",sources:AskSource[]){let v:any;try{v=JSON.parse(raw)}catch{throw new Error('ask reading returned invalid JSON')}const answer=clean(v.answer,1800);if(!answer)throw new Error('ask reading answer missing');const allowed=new Map(sources.map(s=>[`${s.sourceType}:${s.sourceId}`,s]));const refs=Array.isArray(v.sourceRefs)?v.sourceRefs.slice(0,8).map((r:any)=>allowed.get(`${clean(r?.sourceType,40)}:${clean(r?.sourceId,100)}`)).filter(Boolean).map((s:any)=>({sourceType:s.sourceType,sourceId:s.sourceId,bookTitle:s.bookTitle,occurredAt:s.occurredAt})):[];if(sources.length&&!refs.length)throw new Error('ask reading returned no valid sources');return {outputLanguage:language,answer,sourceRefs:refs};}
export async function searchAskReadingSources(ownerId:string,question:string):Promise<AskSource[]>{const q=question.replace(/[\%_]/g,' ').trim().slice(0,120);const rows=(await query<any>(`WITH sources AS (SELECT 'log' source_type,rl.id::text source_id,rl.book_id,b.title book_title,rl.date::text occurred_at,concat_ws(E'\n',rl.summary,array_to_string(rl.key_insights,'; '),rl.notes,rl.quote) content FROM reading_log rl JOIN books b ON b.id=rl.book_id WHERE b.owner_id=$1 UNION ALL SELECT 'lens',r.id::text,r.book_id,b.title,r.generated_at::text,concat_ws(E'\n',r.analyst_summary,r.analysis::text) FROM reading_lens_analyses r JOIN books b ON b.id=r.book_id WHERE b.owner_id=$1 UNION ALL SELECT 'wiki',w.book_id::text,w.book_id,b.title,w.generated_at::text,concat_ws(E'\n',w.overview,w.book_so_far,w.notable_quotes::text,w.chapter_map::text,w.connections::text) FROM book_wiki w JOIN books b ON b.id=w.book_id WHERE b.owner_id=$1) SELECT * FROM sources WHERE content ILIKE '%'||$2||'%' ORDER BY occurred_at DESC LIMIT 24`,[ownerId,q])).rows;if (!rows.length) { const fallback=(await query<any>(`SELECT 'log' source_type,rl.id::text source_id,rl.book_id,b.title book_title,rl.date::text occurred_at,concat_ws(E'
',rl.summary,array_to_string(rl.key_insights,'; '),rl.notes,rl.quote) content FROM reading_log rl JOIN books b ON b.id=rl.book_id WHERE b.owner_id=$1 AND (rl.summary IS NOT NULL OR cardinality(rl.key_insights)>0 OR rl.notes IS NOT NULL OR rl.quote IS NOT NULL) ORDER BY rl.date DESC,rl.session DESC LIMIT 12`,[ownerId])).rows; rows.push(...fallback); } return rows.map((r:any)=>({sourceType:r.source_type,sourceId:r.source_id,bookId:r.book_id,bookTitle:r.book_title,occurredAt:r.occurred_at,content:clean(r.content,2200)}));}
export async function getAskReadingAnswer(ownerId:string,requestKey:string):Promise<AskAnswer|null>{const r=(await query<any>('SELECT id,request_key,question,output_language,answer,source_refs,source_count,created_at FROM ask_reading_answers WHERE owner_id=$1 AND request_key=$2',[ownerId,requestKey])).rows[0];return r?{id:r.id,requestKey:r.request_key,question:r.question,outputLanguage:r.output_language,answer:r.answer,sourceRefs:r.source_refs,sourceCount:Number(r.source_count),createdAt:new Date(r.created_at).toISOString()}:null;}
export async function recentAskReading(ownerId:string){const rows=(await query<any>('SELECT id,request_key,question,output_language,answer,source_refs,source_count,created_at FROM ask_reading_answers WHERE owner_id=$1 ORDER BY created_at DESC LIMIT 20',[ownerId])).rows;return rows.map((r:any)=>({id:r.id,requestKey:r.request_key,question:r.question,outputLanguage:r.output_language,answer:r.answer,sourceRefs:r.source_refs,sourceCount:Number(r.source_count),createdAt:new Date(r.created_at).toISOString()}));}
export async function answerAskReading(ownerId:string,question:unknown,requestKey?:unknown){const q=normalizeQuestion(question);const key=clean(requestKey,160)||`ask:${crypto.randomUUID()}`;const old=await getAskReadingAnswer(ownerId,key);if(old)return {status:'existing' as const,answer:old};const sources=await searchAskReadingSources(ownerId,q);if(!hasRelevantSource(sources))return {status:'no_source' as const,answer:null};const language=resolveOutputLanguage(q,sources);const reservation=await reserveUsage({userId:ownerId,feature:'ask_my_reading',requestKey:key,resource:{type:'ask_reading',id:key}});try{const parsed=parseAskReading(await callJsonLLM('You are a careful reading companion. Return strict JSON only.',buildAskReadingPrompt(q,language,sources),0.2),language,sources);const saved=(await query<any>(`INSERT INTO ask_reading_answers(owner_id,request_key,question,output_language,answer,source_refs,source_count,schema_version) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id,created_at`,[ownerId,key,q,language,parsed.answer,JSON.stringify(parsed.sourceRefs),sources.length,ASK_READING_SCHEMA_VERSION])).rows[0];await consumeUsage(reservation.id);return {status:'answered' as const,answer:{...parsed,id:saved.id,requestKey:key,question:q,sourceCount:sources.length,createdAt:new Date(saved.created_at).toISOString()}};}catch(e){await releaseUsage(reservation.id,e instanceof Error?e.message:'answer failed');throw e;}}
