import { query } from "./db.js";
import { buildSearchDocument, normalizeLibrarySearchText, safeSearchExcerpt, type LibrarySearchKind, type LibrarySearchResult, type SearchDocumentInput } from "./librarySearch.js";

export async function upsertSearchDocument(input: SearchDocumentInput): Promise<void> { const doc = buildSearchDocument(input); if (!doc) return; const normalized = normalizeLibrarySearchText(`${doc.title}\n${doc.body}`); await query(`INSERT INTO search_documents (owner_id,book_id,reading_round,log_id,kind,source_key,title,body,normalized_text,page_start,page_end,search_vector,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,to_tsvector('simple',$9),now()) ON CONFLICT (owner_id,kind,source_key) DO UPDATE SET book_id=EXCLUDED.book_id,reading_round=EXCLUDED.reading_round,log_id=EXCLUDED.log_id,title=EXCLUDED.title,body=EXCLUDED.body,normalized_text=EXCLUDED.normalized_text,page_start=EXCLUDED.page_start,page_end=EXCLUDED.page_end,search_vector=EXCLUDED.search_vector,updated_at=now()`, [doc.ownerId,doc.bookId,doc.readingRound || null,doc.logId || null,doc.kind,doc.sourceKey,doc.title,doc.body,normalized,doc.pageStart || null,doc.pageEnd || null]); }
export async function deleteSearchDocument(ownerId: string, kind: LibrarySearchKind, sourceKey: string): Promise<void> { await query("DELETE FROM search_documents WHERE owner_id=$1 AND kind=$2 AND source_key=$3", [ownerId,kind,sourceKey]); }
export async function searchLibrary(ownerId: string, input: { q: string; kind?: LibrarySearchKind; bookId?: string; limit?: number }): Promise<LibrarySearchResult[]> { const q = input.q.trim().slice(0,120); if (q.length < 2) return []; const normalized = normalizeLibrarySearchText(q); const params: unknown[]=[ownerId,q,normalized]; const filters=["d.owner_id=$1", "(d.search_vector @@ websearch_to_tsquery('simple',$2) OR d.normalized_text LIKE '%' || $3 || '%')"]; if(input.kind){params.push(input.kind);filters.push(`d.kind=$${params.length}`)} if(input.bookId){params.push(input.bookId);filters.push(`d.book_id=$${params.length}`)} params.push(Math.min(30,Math.max(1,input.limit || 24))); const {rows}=await query<any>(`SELECT d.kind,d.book_id AS "bookId",b.title AS "bookTitle",b.author AS "bookAuthor",d.reading_round AS "readingRound",d.log_id AS "logId",d.page_start AS "pageStart",d.page_end AS "pageEnd",d.title,d.body,CASE WHEN d.normalized_text LIKE '%' || $3 || '%' THEN 2 ELSE 0 END + ts_rank_cd(d.search_vector,websearch_to_tsquery('simple',$2)) AS rank FROM search_documents d JOIN books b ON b.id=d.book_id WHERE ${filters.join(" AND ")} ORDER BY rank DESC,d.updated_at DESC LIMIT $${params.length}`,params); return rows.map((r:any)=>({...r,rank:Number(r.rank)||0,excerpt:safeSearchExcerpt(r.body,q)})); }

export async function bestEffortUpsertSearchDocument(input: SearchDocumentInput): Promise<void> { try { await upsertSearchDocument(input); } catch (error) { console.warn("[library-search] index upsert skipped", error instanceof Error ? error.message : error); } }
export async function bestEffortDeleteSearchDocument(ownerId: string, kind: LibrarySearchKind, sourceKey: string): Promise<void> { try { await deleteSearchDocument(ownerId, kind, sourceKey); } catch (error) { console.warn("[library-search] index delete skipped", error instanceof Error ? error.message : error); } }
