import { query } from "./db.js";
import type { JourneySynthesis } from "./journeySynthesis.js";
export type ReadingLensSynthesisRow={book_id:string;schema_version:number;through_line:string;evolving_concepts:any[];resolved_questions:any[];open_questions:string[];tensions:any[];confidence_notes:string[];output_language:"vi"|"en";sessions_covered:number;last_log_id:string|null;last_log_date:string|null;last_log_session:number|null;source_revision:number;stale:boolean;generated_at:string};
export type SynthesisWatermark={logId:string;date:string;session:number};
export async function getSynthesis(bookId:string, round?:number){
  if (!round) return (await query<ReadingLensSynthesisRow>("SELECT * FROM reading_lens_synthesis WHERE book_id=$1",[bookId])).rows[0]||null;
  return (await query<ReadingLensSynthesisRow>(
    "SELECT s.* FROM reading_lens_synthesis s JOIN reading_log l ON l.id=s.last_log_id WHERE s.book_id=$1 AND l.reading_round=$2",[bookId,round])).rows[0]||null;
}
export async function upsertSynthesis(bookId:string,d:JourneySynthesis,sessions:number,w:SynthesisWatermark,revision:number){return (await query<ReadingLensSynthesisRow>(`INSERT INTO reading_lens_synthesis(book_id,schema_version,through_line,evolving_concepts,resolved_questions,open_questions,tensions,confidence_notes,output_language,sessions_covered,last_log_id,last_log_date,last_log_session,source_revision,stale) VALUES($1,1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,false) ON CONFLICT(book_id) DO UPDATE SET through_line=EXCLUDED.through_line,evolving_concepts=EXCLUDED.evolving_concepts,resolved_questions=EXCLUDED.resolved_questions,open_questions=EXCLUDED.open_questions,tensions=EXCLUDED.tensions,confidence_notes=EXCLUDED.confidence_notes,output_language=EXCLUDED.output_language,sessions_covered=EXCLUDED.sessions_covered,last_log_id=EXCLUDED.last_log_id,last_log_date=EXCLUDED.last_log_date,last_log_session=EXCLUDED.last_log_session,source_revision=GREATEST(reading_lens_synthesis.source_revision,EXCLUDED.source_revision),stale=false,generated_at=now() WHERE EXCLUDED.source_revision > reading_lens_synthesis.source_revision RETURNING *`,[bookId,d.throughLine,JSON.stringify(d.evolvingConcepts),JSON.stringify(d.resolvedQuestions),JSON.stringify(d.openQuestions),JSON.stringify(d.tensions),JSON.stringify(d.confidenceNotes),d.outputLanguage,sessions,w.logId,w.date,w.session,revision])).rows[0] || await getSynthesis(bookId)!}
/** Mark stale only when a regenerated analysis was already covered by the durable ordered watermark. */
export async function markReadingLensSynthesisStaleIfCovered(bookId:string,logId:string){await query(`UPDATE reading_lens_synthesis s SET stale=true,source_revision=source_revision+1 WHERE s.book_id=$1 AND NOT s.stale AND EXISTS (SELECT 1 FROM reading_log l WHERE l.id=$2 AND l.book_id=$1 AND s.last_log_date IS NOT NULL AND (l.date,l.session,l.id) <= (s.last_log_date,s.last_log_session,s.last_log_id))`,[bookId,logId])}
