import { callLLM } from "./llm.js";

export type ReferenceCardType = "recipe" | "formula" | "procedure";
export type RecipeFields = { servings: string | null; ingredients: Array<{ item: string; amount: string | null }>; steps: string[]; nutrition: string[]; substitutions: string[] };
export type FormulaFields = { expression: string; variables: Array<{ symbol: string; meaning: string; unit: string | null }>; conditions: string[]; steps: string[]; example: string | null };
export type ProcedureFields = { prerequisites: string[]; steps: string[]; checklist: string[]; expectedOutcome: string | null };
export type ReferenceCardFields = RecipeFields | FormulaFields | ProcedureFields;
export type ReferenceCardDraft = { cardType: ReferenceCardType; title: string; content: string; fields: ReferenceCardFields; tags: string[]; sourceExcerpt: string; personalAdaptation?: string; needsReview: boolean };
const types: ReferenceCardType[] = ["recipe", "formula", "procedure"];
const text = (value: unknown, max: number) => typeof value === "string" ? value.replace(/\0/g, "").trim().slice(0, max) : "";
const strings = (value: unknown, max = 50) => Array.isArray(value) ? value.map(v => text(v, 500)).filter(Boolean).slice(0, max) : [];
const object = (value: unknown): Record<string, unknown> => value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {};
export const emptyFieldsFor = (type: ReferenceCardType): ReferenceCardFields => type === "recipe" ? { servings: null, ingredients: [], steps: [], nutrition: [], substitutions: [] } : type === "formula" ? { expression: "", variables: [], conditions: [], steps: [], example: null } : { prerequisites: [], steps: [], checklist: [], expectedOutcome: null };
export function normalizeTags(value: unknown): string[] { const seen = new Set<string>(); return (Array.isArray(value) ? value : []).map(v => text(v, 40)).filter(v => { const key=v.toLocaleLowerCase(); if (!v || seen.has(key)) return false; seen.add(key); return true; }).slice(0, 10); }
function fieldsFor(type: ReferenceCardType, value: unknown): ReferenceCardFields { const row=object(value); if(type === "recipe") return { servings: text(row.servings,500)||null, ingredients: (Array.isArray(row.ingredients)?row.ingredients:[]).slice(0,50).map(v=>{const x=object(v);return {item:text(x.item,500),amount:text(x.amount,500)||null};}).filter(v=>v.item), steps:strings(row.steps), nutrition:strings(row.nutrition), substitutions:strings(row.substitutions) }; if(type === "formula") return { expression:text(row.expression,500), variables:(Array.isArray(row.variables)?row.variables:[]).slice(0,50).map(v=>{const x=object(v);return {symbol:text(x.symbol,500),meaning:text(x.meaning,500),unit:text(x.unit,500)||null};}).filter(v=>v.symbol&&v.meaning), conditions:strings(row.conditions), steps:strings(row.steps), example:text(row.example,500)||null }; return { prerequisites:strings(row.prerequisites), steps:strings(row.steps), checklist:strings(row.checklist), expectedOutcome:text(row.expectedOutcome,500)||null }; }
export function normalizeReferenceCardDraft(raw: unknown): ReferenceCardDraft { const row=object(raw); const cardType=types.includes(row.cardType as ReferenceCardType) ? row.cardType as ReferenceCardType : "procedure"; return { cardType, title:text(row.title,160), content:text(row.content,4000), fields:fieldsFor(cardType,row.fields), tags:normalizeTags(row.tags), sourceExcerpt:text(row.sourceExcerpt,12000), personalAdaptation:text(row.personalAdaptation,2000), needsReview: row.needsReview === true }; }
export function sourceExcerptMatches(rawText: string, excerpt: string): boolean { return rawText.replace(/\r\n?/g,"\n").normalize("NFC").includes(excerpt.replace(/\r\n?/g,"\n").normalize("NFC")); }
export function validateReferenceCardPayload(raw: unknown): { ok: true; value: ReferenceCardDraft } | { ok: false; error: string } { const v=normalizeReferenceCardDraft(raw); if(!v.title) return {ok:false,error:"title must be between 1 and 160 characters"}; if(!v.content) return {ok:false,error:"content must be between 1 and 4000 characters"}; if(!v.sourceExcerpt) return {ok:false,error:"sourceExcerpt must be between 1 and 12000 characters"}; if(v.cardType === "formula" && !(v.fields as FormulaFields).expression) return {ok:false,error:"formula expression is required"}; return {ok:true,value:v}; }
export function referenceCardSearchBody(card: Pick<ReferenceCardDraft,"content"|"fields"|"tags"|"personalAdaptation">): string { return [card.content, ...card.tags, card.personalAdaptation || "", JSON.stringify(card.fields)].join("\n"); }
function parseJson(raw: string): unknown { const body=raw.match(/```(?:json)?\s*([\s\S]*?)\s*```/i)?.[1] || raw; const start=body.indexOf("{"); const end=body.lastIndexOf("}"); if(start<0||end<=start) throw new Error("draft response was not JSON"); return JSON.parse(body.slice(start,end+1)); }
export const REFERENCE_CARD_MAX_SOURCE_CHARS=24_000;
export async function extractReferenceCardDraft(input: { title:string; author:string; fileType:"pdf"|"epub"; pageStart:number; pageEnd:number; rawText:string; preferredType?: ReferenceCardType | null; summaryLang?: "auto"|"vi"|"en" }): Promise<ReferenceCardDraft> { const source=input.rawText.slice(0,REFERENCE_CARD_MAX_SOURCE_CHARS); const system=`Extract exactly one reusable recipe, formula, or procedure from ONLY the supplied source. Return strict JSON with cardType,title,content,fields,tags,sourceExcerpt,needsReview. sourceExcerpt MUST be copied verbatim from source. Preserve every quantity, unit, operator and condition. Never use outside knowledge or invent missing values: use null or [] and needsReview:true when source is incomplete, ambiguous, or lacks important steps/variables. Fields: recipe {servings,ingredients:[{item,amount}],steps,nutrition,substitutions}; formula {expression,variables:[{symbol,meaning,unit}],conditions,steps,example}; procedure {prerequisites,steps,checklist,expectedOutcome}.`; const user=`Book: ${input.title} — ${input.author}\nType: ${input.fileType}; position: ${input.pageStart}-${input.pageEnd}\nPreferred type (hint only): ${input.preferredType || "none"}\nSOURCE:\n${source}`; const started=Date.now(); try { const raw=await callLLM(system,user,0.1,true,true,undefined,{priority:"interactive",traceLabel:"reference-card"}); const checked=validateReferenceCardPayload(parseJson(raw)); if(!checked.ok) throw new Error((checked as { ok:false; error:string }).error); if(!sourceExcerptMatches(input.rawText,checked.value.sourceExcerpt)) throw new Error("sourceExcerpt must match the saved session exactly"); console.info(`[reference-card] draft type=${checked.value.cardType} source_chars=${source.length} duration_ms=${Date.now()-started}`); return checked.value; } catch(error) { console.warn(`[reference-card] draft failed source_chars=${source.length} duration_ms=${Date.now()-started}`); throw error; } }
