import { query, withTransaction } from "./db.js";
import { bestEffortDeleteSearchDocument, bestEffortUpsertSearchDocument } from "./librarySearchRepository.js";
import { referenceCardSearchBody, type ReferenceCardDraft, type ReferenceCardType } from "./referenceCards.js";
export type ReferenceSource={book_id:string; reading_round:number; log_id:string; page_start:number; page_end:number; raw_text:string; title:string; author:string; file_type:"pdf"|"epub"; status:string; summary_lang:"auto"|"vi"|"en"};
export class ReferenceCardError extends Error { constructor(public status:number,message:string){super(message)} }
const cardSelect=`SELECT c.*,b.title AS book_title,b.author AS book_author,b.file_type,b.status AS book_status,COALESCE(u.usage_count,0)::int AS usage_count,u.last_used_at FROM reference_cards c JOIN books b ON b.id=c.book_id LEFT JOIN LATERAL (SELECT count(*) AS usage_count,max(used_at) AS last_used_at FROM reference_card_uses WHERE card_id=c.id) u ON true`;
function map(row:any){return {...row, fields:typeof row.fields === "string"?JSON.parse(row.fields):row.fields, cardType:row.card_type, personalAdaptation:row.personal_adaptation, sourceExcerpt:row.source_excerpt, sourcePageStart:row.source_page_start,sourcePageEnd:row.source_page_end,readingRound:row.reading_round, bookId:row.book_id,logId:row.log_id, needsReview:row.needs_review};}
export async function getReferenceSource(ownerId:string,bookId:string,logId:string):Promise<ReferenceSource>{const {rows}=await query<ReferenceSource>(`SELECT b.id AS book_id,rl.reading_round,rl.id AS log_id,rl.page_start,rl.page_end,rl.raw_text,b.title,b.author,b.file_type,b.status,b.summary_lang FROM books b JOIN reading_log rl ON rl.book_id=b.id WHERE b.id=$1 AND b.owner_id=$2 AND rl.id=$3`,[bookId,ownerId,logId]);const source=rows[0];if(!source)throw new ReferenceCardError(404,"saved session not found");if(source.status === "paused")throw new ReferenceCardError(409,"Resume this book to change or use its cards.");if(!source.raw_text?.trim())throw new ReferenceCardError(422,"session has no extracted text");return source;}
export async function listReferenceCards(ownerId:string,filters:{q?:string;type?:ReferenceCardType;bookId?:string;sort?:string;limit?:number;offset?:number}){const params:any[]=[ownerId], where=["c.owner_id=$1"];if(filters.type){params.push(filters.type);where.push(`c.card_type=$${params.length}`)}if(filters.bookId){params.push(filters.bookId);where.push(`c.book_id=$${params.length}`)}if(filters.q?.trim()){params.push(`%${filters.q.trim().slice(0,120)}%`);where.push(`(c.title ILIKE $${params.length} OR c.content ILIKE $${params.length} OR c.personal_adaptation ILIKE $${params.length} OR array_to_string(c.tags,' ') ILIKE $${params.length})`)}const sort=filters.sort==="title"?"c.title ASC,c.id ASC":filters.sort==="recently_saved"?"c.updated_at DESC,c.id DESC":"u.last_used_at DESC NULLS LAST,c.updated_at DESC,c.id DESC";params.push(Math.min(50,Math.max(1,filters.limit||24)),Math.max(0,filters.offset||0));const {rows}=await query<any>(`${cardSelect} WHERE ${where.join(" AND ")} ORDER BY ${sort} LIMIT $${params.length-1} OFFSET $${params.length}`,params);return rows.map(map);}
export async function getReferenceCard(ownerId:string,cardId:string){const {rows}=await query<any>(`${cardSelect} WHERE c.owner_id=$1 AND c.id=$2`,[ownerId,cardId]);return rows[0]?map(rows[0]):null;}
export async function createReferenceCard(ownerId:string,input:{requestKey:string;bookId:string;logId:string;draft:ReferenceCardDraft}){const row=await withTransaction(async client=>{const source=(await client.query(`SELECT b.id AS book_id,b.status,rl.reading_round,rl.page_start,rl.page_end,rl.raw_text FROM books b JOIN reading_log rl ON rl.book_id=b.id WHERE b.id=$1 AND b.owner_id=$2 AND rl.id=$3 FOR UPDATE`,[input.bookId,ownerId,input.logId])).rows[0];if(!source)throw new ReferenceCardError(404,"saved session not found");if(source.status === "paused")throw new ReferenceCardError(409,"Resume this book to change or use its cards.");if(!source.raw_text?.replace(/\r\n?/g,"\n").normalize("NFC").includes(input.draft.sourceExcerpt.replace(/\r\n?/g,"\n").normalize("NFC")))throw new ReferenceCardError(422,"sourceExcerpt must match the saved session exactly");const existing=(await client.query("SELECT id FROM reference_cards WHERE owner_id=$1 AND request_key=$2",[ownerId,input.requestKey])).rows[0];if(existing)return existing;return (await client.query(`INSERT INTO reference_cards(owner_id,book_id,reading_round,log_id,request_key,card_type,title,content,fields,tags,personal_adaptation,source_excerpt,source_page_start,source_page_end,needs_review) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10,$11,$12,$13,$14,$15) RETURNING id`,[ownerId,input.bookId,source.reading_round,input.logId,input.requestKey,input.draft.cardType,input.draft.title,input.draft.content,JSON.stringify(input.draft.fields),input.draft.tags,input.draft.personalAdaptation||"",input.draft.sourceExcerpt,source.page_start,source.page_end,input.draft.needsReview])).rows[0];});const card=await getReferenceCard(ownerId,row.id);if(card) await bestEffortUpsertSearchDocument({ownerId,bookId:card.book_id,readingRound:card.reading_round,logId:card.log_id,kind:"reference_card",sourceKey:card.id,title:card.title,body:referenceCardSearchBody({content:card.content,fields:card.fields,tags:card.tags,personalAdaptation:card.personal_adaptation}) ,pageStart:card.source_page_start,pageEnd:card.source_page_end});return card!;}
async function mutable(ownerId:string,cardId:string,client:any){const row=(await client.query(`${cardSelect} WHERE c.owner_id=$1 AND c.id=$2 FOR UPDATE`,[ownerId,cardId])).rows[0];if(!row)throw new ReferenceCardError(404,"playbook card not found");if(row.book_status === "paused")throw new ReferenceCardError(409,"Resume this book to change or use its cards.");return row;}
export async function updateReferenceCard(ownerId:string,cardId:string,draft:ReferenceCardDraft){await withTransaction(async client=>{await mutable(ownerId,cardId,client);await client.query(`UPDATE reference_cards SET card_type=$1,title=$2,content=$3,fields=$4::jsonb,tags=$5,personal_adaptation=$6,needs_review=$7,updated_at=now() WHERE id=$8 AND owner_id=$9`,[draft.cardType,draft.title,draft.content,JSON.stringify(draft.fields),draft.tags,draft.personalAdaptation||"",draft.needsReview,cardId,ownerId]);});const card=await getReferenceCard(ownerId,cardId);if(card)await bestEffortUpsertSearchDocument({ownerId,bookId:card.book_id,readingRound:card.reading_round,logId:card.log_id,kind:"reference_card",sourceKey:card.id,title:card.title,body:referenceCardSearchBody({content:card.content,fields:card.fields,tags:card.tags,personalAdaptation:card.personal_adaptation}),pageStart:card.source_page_start,pageEnd:card.source_page_end});return card!;}
export async function deleteReferenceCard(ownerId:string,cardId:string){await withTransaction(async client=>{await mutable(ownerId,cardId,client);await client.query("DELETE FROM reference_cards WHERE id=$1 AND owner_id=$2",[cardId,ownerId]);});await bestEffortDeleteSearchDocument(ownerId,"reference_card",cardId);}
export async function recordReferenceCardUse(ownerId:string,cardId:string,input:{requestKey:string;note:string}){return withTransaction(async client=>{await mutable(ownerId,cardId,client);const {rows}=await client.query(`INSERT INTO reference_card_uses(card_id,owner_id,request_key,note) VALUES($1,$2,$3,$4) ON CONFLICT(owner_id,request_key) DO UPDATE SET request_key=EXCLUDED.request_key RETURNING *`,[cardId,ownerId,input.requestKey,input.note]);return rows[0];});}
export async function listReferenceCardUses(ownerId:string,cardId:string){const {rows}=await query("SELECT id,note,used_at FROM reference_card_uses WHERE owner_id=$1 AND card_id=$2 ORDER BY used_at DESC,id DESC LIMIT 50",[ownerId,cardId]);return rows;}
